#!/bin/bash
set -e

cd "$(dirname "$0")"

src_dir="$1"
target_dir="./entry"
results_dir="./results" 

if [ -z "$src_dir" ] || [ ! -d "$src_dir" ]; then
    echo "ERROR: Source directory does not exist or was not provided!"
    exit 1
fi

echo "Cleaning up old files..."
rm -rf "$target_dir"
rm -rf "$results_dir"
mkdir -p "$target_dir"
mkdir -p "$results_dir"

ls
echo "Copying files..."
cp -r "$src_dir"/. "$target_dir"/


echo "Building docker instance..."
docker build --tag "run_tests" .


echo "Running tests in Docker... (Please wait)"

docker run --rm \
    --name "my_test_runner" \
    -v "$(pwd)/results:/test/test_files/sum" \
    "run_tests"

echo "Docker container finished and cleaned up."

if [ -f "$results_dir/result.md" ]; then
    echo "SUCCESS: Results extracted safely to $results_dir/result.md"
    cat "$results_dir/result.md"
else
    echo "ERROR: result.md was not generated by the container."
fi
